# Generated by Django 5.0.6 on 2024-11-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
