# Generated by Django 5.0.6 on 2024-11-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='crypto_wallet',
            field=models.CharField(max_length=255),
        ),
    ]
