# Generated by Django 5.0.6 on 2024-11-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='number_of_clicks',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
