# Generated by Django 5.0.6 on 2024-11-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the wallet (e.g., Bitcoin, Ethereum).', max_length=255)),
                ('network', models.CharField(help_text='The blockchain network (e.g., Mainnet, Testnet).', max_length=255)),
                ('address', models.CharField(help_text='The unique wallet address.', max_length=255, unique=True)),
            ],
        ),
    ]
