# Generated by Django 5.0.6 on 2024-11-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_plans', '0002_plan_number_of_clicks'),
        ('manage_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plans',
            field=models.ManyToManyField(related_name='products', to='manage_plans.plan'),
        ),
    ]
