# Generated by Django 5.0.6 on 2024-11-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_profile_balance_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='client',
            new_name='profile',
        ),
    ]
