# Generated by Django 5.0.6 on 2024-11-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_client_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='customers',
        ),
    ]
