# Generated by Django 5.0.6 on 2024-11-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_profile_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
