# Generated by Django 5.0.6 on 2024-11-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_profile_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='successful_checkouts',
            field=models.IntegerField(default=0),
        ),
    ]
