# Generated by Django 5.0.6 on 2024-11-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_profile_successful_checkouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='super_bonus_mode',
            field=models.BooleanField(default=False),
        ),
    ]
