# Generated by Django 5.1.3 on 2024-12-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_profile_super_bonus_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_checkouts',
            field=models.IntegerField(default=0),
        ),
    ]
